In [ ]:
content=['data science important field science',
 'important data science course',
 'cars driven roads',
 'trucks driven highways']

In [ ]:
def extract_vocabulary(corpus):
  vocab=set()
  for sentence in corpus:
    for word in sentence.split():
      vocab.add(word)
  return (sorted(vocab))
  #print(vocab)



In [ ]:
vocab=extract_vocabulary(content)

#DTM

In [ ]:
def create_DTM(corpus,vocab):
  dtm=[]
  for sentence in corpus:
    row=[0]*len(vocab)
    for word in sentence.split():
      i=vocab.index(word)
      if i != -1:
        row[i]+=1
    dtm.append(row)
  return dtm



In [ ]:
print(create_DTM(content,vocab))

[[0, 0, 1, 0, 1, 0, 1, 0, 2, 0], [0, 1, 1, 0, 0, 0, 1, 0, 1, 0], [1, 0, 0, 1, 0, 0, 0, 1, 0, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0, 1]]


In [ ]:
import pandas as pd
df=pd.DataFrame(create_DTM(content,vocab),columns=vocab)
df

cars  course  data  driven  field  highways  important  roads  science  \
0     0       0     1       0      1         0          1      0        2   
1     0       1     1       0      0         0          1      0        1   
2     1       0     0       1      0         0          0      1        0   
3     0       0     0       1      0         1          0      0        0   

   trucks  
0       0  
1       0  
2       0  
3       1

#Binary DTM

In [ ]:
def create_BinaryDTM(corpus,vocab):
  dtm=[]
  for sentence in corpus:
    row=[0]*len(vocab)
    for word in sentence.split():
      i=vocab.index(word)
      if i != -1:
        row[i]=1
    dtm.append(row)
  return dtm

In [ ]:
import pandas as pd
df=pd.DataFrame(create_BinaryDTM(content,vocab),columns=vocab)
df

cars  course  data  driven  field  highways  important  roads  science  \
0     0       0     1       0      1         0          1      0        1   
1     0       1     1       0      0         0          1      0        1   
2     1       0     0       1      0         0          0      1        0   
3     0       0     0       1      0         1          0      0        0   

   trucks  
0       0  
1       0  
2       0  
3       1

#Binary TDM

In [ ]:
import numpy as np
numpy_array = np.array(create_BinaryDTM(content,vocab))
print(numpy_array.T)

[[0 0 1 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [1 0 0 0]
 [0 0 0 1]
 [1 1 0 0]
 [0 0 1 0]
 [1 1 0 0]
 [0 0 0 1]]


In [ ]:
import pandas as pd
df=pd.DataFrame(numpy_array.T,index=vocab)
df

0  1  2  3
cars       0  0  1  0
course     0  1  0  0
data       1  1  0  0
driven     0  0  1  1
field      1  0  0  0
highways   0  0  0  1
important  1  1  0  0
roads      0  0  1  0
science    1  1  0  0
trucks     0  0  0  1

In [ ]:
# Initialize an empty list to hold the matrix
import pandas as pd

def create_TDM(content,vocab):
  tdm = []
  # Iterate over each term in unique_terms
  for term in vocab:
      # Create a row for the current term
      row = []
      # Check the presence of the term in each document
      for doc in content:
          if term in doc.split():
              row.append(1)
          else:
              row.append(0)
      # Append the row to the TDM
      tdm.append(row)
   # Convert the TDM to a DataFrame for better visualization (optional)

  tdm_df = pd.DataFrame(tdm, index=vocab)
  print(tdm_df)


0.0003294944763183594
           0  1  2  3
cars       0  0  1  0
course     0  1  0  0
data       1  1  0  0
driven     0  0  1  1
field      1  0  0  0
highways   0  0  0  1
important  1  1  0  0
roads      0  0  1  0
science    1  1  0  0
trucks     0  0  0  1


#Term Term Matrix

In [ ]:
z=np.dot(numpy_array.T,numpy_array)

for i in range(z.shape[0]):
  z[i][i]=0
print(z)


[[0 0 0 1 0 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 1 0]
 [0 1 0 0 1 0 2 0 2 0]
 [1 0 0 0 0 1 0 1 0 1]
 [0 0 1 0 0 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 1]
 [0 1 2 0 1 0 0 0 2 0]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 2 0 1 0 2 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]]


In [ ]:
import pandas as pd
df=pd.DataFrame(z,index=vocab,columns=vocab)
df

cars  course  data  driven  field  highways  important  roads  \
cars          0       0     0       1      0         0          0      1   
course        0       0     1       0      0         0          1      0   
data          0       1     0       0      1         0          2      0   
driven        1       0     0       0      0         1          0      1   
field         0       0     1       0      0         0          1      0   
highways      0       0     0       1      0         0          0      0   
important     0       1     2       0      1         0          0      0   
roads         1       0     0       1      0         0          0      0   
science       0       1     2       0      1         0          2      0   
trucks        0       0     0       1      0         1          0      0   

           science  trucks  
cars             0       0  
course           1       0  
data             2       0  
driven           0       1  
field            1       0  
highways         0       1  
important        2       0  
roads            0       0  
science          0       0  
trucks           0       0

In [ ]:
content=['data scienc import field scienc',
 'thi import data scienc cours',
 'the car driven road',
 'the truck driven highway']
vocab=extract_vocabulary(content)
vocab

['car',
 'cours',
 'data',
 'driven',
 'field',
 'highway',
 'import',
 'road',
 'scienc',
 'the',
 'thi',
 'truck']

In [ ]:
def create_TDM(corpus,vocab):
  tdm=[]
  for sentence in corpus:
    col=[0]*len(vocab)
    for word in sentence.split():
      i=vocab.index(word)
      if i != -1:
        col[i]+=1
    tdm.append(col)
  return tdm

In [ ]:
x=create_TDM(content,vocab)
x

[[0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0],
 [1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1]]

In [ ]:
import pandas as pd
x=create_TDM(content,vocab)

df2=pd.DataFrame(np.array(x).T,index=vocab)
df2

0  1  2  3
car      0  0  1  0
cours    0  1  0  0
data     1  1  0  0
driven   0  0  1  1
field    1  0  0  0
highway  0  0  0  1
import   1  1  0  0
road     0  0  1  0
scienc   2  1  0  0
the      0  0  1  1
thi      0  1  0  0
truck    0  0  0  1

#TDM with length normalization

In [ ]:
df3=df2.div(df2.sum(axis=0), axis=1)
df3

0    1     2     3
car      0.0  0.0  0.25  0.00
cours    0.0  0.2  0.00  0.00
data     0.2  0.2  0.00  0.00
driven   0.0  0.0  0.25  0.25
field    0.2  0.0  0.00  0.00
highway  0.0  0.0  0.00  0.25
import   0.2  0.2  0.00  0.00
road     0.0  0.0  0.25  0.00
scienc   0.4  0.2  0.00  0.00
the      0.0  0.0  0.25  0.25
thi      0.0  0.2  0.00  0.00
truck    0.0  0.0  0.00  0.25

# TDM  with max normalization

In [ ]:
df4=df2.div(df2.max(axis=0), axis=1)
df4

0    1    2    3
car      0.0  0.0  1.0  0.0
cours    0.0  1.0  0.0  0.0
data     0.5  1.0  0.0  0.0
driven   0.0  0.0  1.0  1.0
field    0.5  0.0  0.0  0.0
highway  0.0  0.0  0.0  1.0
import   0.5  1.0  0.0  0.0
road     0.0  0.0  1.0  0.0
scienc   1.0  1.0  0.0  0.0
the      0.0  0.0  1.0  1.0
thi      0.0  1.0  0.0  0.0
truck    0.0  0.0  0.0  1.0

#CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample dataset
documents = [
    "Machine learning is fascinating.",
    "Data science and machine learning go hand in hand.",
    "Deep learning is a subset of machine learning.",
    "Python is great for machine learning.",
    "Data science is about extracting knowledge from data."
]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Get feature names (i.e., the vocabulary)
feature_names = vectorizer.get_feature_names_out()
#vocabulary_: Returns a dictionary mapping features to indices.
vocab = vectorizer.vocabulary_

# Convert the result to an array
X_array = X.toarray()

# Print the results
print("Feature Names:", feature_names)
print("Vocab:", vocab)

print("Document-Term Matrix:")
print(X_array)


Feature Names: ['about' 'and' 'data' 'deep' 'extracting' 'fascinating' 'for' 'from' 'go'
 'great' 'hand' 'in' 'is' 'knowledge' 'learning' 'machine' 'of' 'python'
 'science' 'subset']
Vocab: {'machine': 15, 'learning': 14, 'is': 12, 'fascinating': 5, 'data': 2, 'science': 18, 'and': 1, 'go': 8, 'hand': 10, 'in': 11, 'deep': 3, 'subset': 19, 'of': 16, 'python': 17, 'great': 9, 'for': 6, 'about': 0, 'extracting': 4, 'knowledge': 13, 'from': 7}
Document-Term Matrix:
[[0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 1 0 2 1 0 0 1 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 2 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0]
 [1 0 2 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0]]


# Initialize CountVectorizer with parameters

vectorizer
= CountVectorizer(

    stop_words='english',  # Remove common English stop words

    ngram_range=(1, 2),    # Include both unigrams and bigrams
    
    max_df=0.95,           # Ignore words that appear in more than 95% of documents
    
    min_df=2               # Ignore words that appear in fewer than 2 documents

    binary=True

    max_features=5  # Limit the number of features (tokens) to 5.  ordered by term frequency across the corpus.

    lowercase=True
    
)



custom_stop_words = ['is', 'and', 'for']

vectorizer = CountVectorizer(stop_words=custom_stop_words)


#TFIDF from scratch

In [ ]:
content=['data scienc import field scienc',
 'thi import data scienc cours',
 'the car driven road',
 'the truck driven highway']

In [ ]:
vocab=extract_vocabulary(content)

In [ ]:
d={}
for term in vocab:
  d[term] = 0
  for sentence in content:
    if term in sentence.split():
      d[term] += 1




In [ ]:
import numpy as np
idf={}
for term in vocab:
  idf[term]=np.log10(len(content)/d[term])
  print(idf[term])


0.6020599913279624
0.6020599913279624
0.3010299956639812
0.3010299956639812
0.6020599913279624
0.6020599913279624
0.3010299956639812
0.6020599913279624
0.3010299956639812
0.3010299956639812
0.6020599913279624
0.6020599913279624


In [ ]:
idf

{'car': 0.6020599913279624,
 'cours': 0.6020599913279624,
 'data': 0.3010299956639812,
 'driven': 0.3010299956639812,
 'field': 0.6020599913279624,
 'highway': 0.6020599913279624,
 'import': 0.3010299956639812,
 'road': 0.6020599913279624,
 'scienc': 0.3010299956639812,
 'the': 0.3010299956639812,
 'thi': 0.6020599913279624,
 'truck': 0.6020599913279624}